### ISSUE TITLE
Highlight if string is in queue; avoid double translation of the same strings

### ISSUE THREAD

**Issue by tormec** [dokufreaks/dokuwiki-translation#85]
If one submit a translation and itsn't immediately marged, it could be that somebody else submit a translation, maybe different, but of the same strings.
So, why don't show a message to inform that those strings were already translated or, better, avoid any translation for those strings there?

**Comment by Klap-in** [comment]
- So far I can remember just an couple of double submits the last years, so I think it is not a big issue..
- For most plugins and dokuwiki itselft, the translations are merged relatively fast.

Some thoughts about possible improvements:
 1. If something is merged it takes some time for the translation tool sees this because it checks at frequency of hours (or even 24hours) the state of the repository.
 2. Store and mark submitted strings. But this requires parsing stored update files and use that info in the displaying of the strings in the interface. Knowing which update files are already merged in the repository, can be performed by comparing dates of update files and the respectively language file in the repository.

improvement 2 is quite an effort and complexity. Is that it worth?

**Comment by splitbrain** [comment]
1. would be simple to improve by using a webhook. This way github could tell us when a branch gets merged

**Comment by Klap-in** [comment]
https://developer.github.com/webhooks/

Should a webhook be set per repository? (so also for each extension?)

**Comment by Klap-in** [comment]
@tormec , with #100 a message is now shown above the translation form with the number of open pull request for the current language. This requires a small effort of the user to investigate the situation, but the system gives at least a hint about the situation.

A string-by-string comparison is technical an extensive job to build into the tool. Therefore I consider that current solution is reasonable trade-off between complexity and user comfort. Or do you see more possibilities to inform?
